// Code generated by goctl. DO NOT EDIT.
package types

type ExampleRequest struct {
	SendMessage string `json:"sendMessage"`
}

type ExampleReply struct {
	ReplyMessage string `json:"replyMessage"`
}

type EmployeeInfoRequest struct {
	EmployeeId string `form:"employeeId"`
}

type EmployeeInfoReply struct {
	EmployeeName string `form:"employeeName"`
}
